### PR TITLE
Lesson progression fix

### PR DESCRIPTION
**Pull request by reedhewitt**
## Description

In the class `LLMS_Blocks_Lesson_Progression_Block` method `get_empty_render_message()` there is a conditional statement that checks if a lesson is free.  However, there can be instances where the current post (as returned by `get_the_ID()`) is not actually a lesson.  The block may be inside a widget or shortcode on a course or regular WordPress page.  This would result in the error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method LLMS_Course::is_free() in /path/to/wordpress/wp-content/plugins/lifterlms/vendor/lifterlms/lifterlms-blocks/includes/blocks/class-llms-blocks-lesson-progression-block.php:64
```

To prevent the error from being thrown, I added `is_a($lesson, 'LLMS_Lesson')` in the conditional statement before the existing call to `$lesson->is_free()`.

## How has this been tested?

The updated code is working fine on my website that uses LifterLMS (https://davidmolnar.com).  The specific place where the error occurred is fixed by this change.

## Types of changes

This update does not change the logic of the code, because the original code was already checking to see if `$lesson` is truthy in case the post could not be retrieved at all.  With my change, if `$lesson` is not an instance of `LLMS_Lesson`, it behaves the same way as if no post could be retrieved.

## Checklist:

- [X] My code has been tested.
- [ ] My code passes all existing automated tests.
- [X] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@reedhewitt thanks for the fix, I'll merge this in next week but may I ask what the reason / requirement for using a lesson-specific block outside of a lesson is? As in, why do you need to put this block somewhere where it causes a fatal?

We should have it fixed (thank you) but I'm trying to understand why you'd want to put this somewhere you shouldn't.

I also can't exactly understand how you'd get the block to show up within a widget/shortcode (as you've cited). To my knowledge you can't use a block in sidebar / widget areas so the error shouldn't really be possible to encounter based on my understanding...

We *intentionally* only register this block on lesson screens to prevent this kind of thing from happening. Of course someone could copy/paste the HTML somewhere. Is this how you've encountered this issue?

**Comment by reedhewitt** [comment]
Hi @thomasplevy,

To be honest, I'm not sure I completely understand it myself.  I found the error while indexing our site with ElasticPress, which hits every post.  It appears that we have an Elementor template for that includes a template for the lesson post type.  Elementor does a lot of that where you create something like a regular post in their post editor, and then that gets used as an element inside another template.  I didn't create all the Elementor templates on the site and I haven't dug in to isolate the exact place where this unusual scenario is originating.  Updating the conditional check to avoid the error was faster and easier, and it didn't have any negative consequences, so that's where I started.

Thanks for the quick response and for including this change!

**Comment by thomasplevy** [comment]
@reedhewitt 

Gotcha, thanks for the info. I kind of figured it was a page builder thing but I wanted to understand it better in case there's some kind of hole with some core functionality that I'm missing.

With full site editing coming I know there's a lot more places that were going to have to harden some of our blocks to ensure they're only used in their intended context.

Full disclosure: we're in the tail end of alpha testing LifterLMS 5.0 and we may not see a LifterLMS core release for another week or two (which would include this). I hope you're not expecting this released imminently and can remain patient while we work on our current priorities.

I will get this merged in next week but more than likely not released for a bit.

Thanks for your patience

**Comment by reedhewitt** [comment]
Thanks, and no problem on the timeline.  I have edited the file on our server, so we are clear of the error for now.

**Pull request merged**
